collabQ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

main/urls.py
from django.urls import path
from .views import HomeView, RegisterView, LoginView, LogoutView, CreateView, AssignView, DashboardView, CompleteView

app_name = "main"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("register", RegisterView.as_view(), name="register"),
    path("login", LoginView.as_view(), name="login"),
    path("create", CreateView.as_view(), name="create"),
    path("assign", AssignView.as_view(), name="assign"),
    path("complete", CompleteView.as_view(), name="complete"),
    path("logout", LogoutView.as_view(), name="logout"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Issue(models.Model):
    STATUS_CHOICES = [
    (1, 'Open'),
    (2, 'Picked'),
    (3, 'Completed'),
    ]

    COMPLEXITY_CHOICES = [
    (1, 'Simple'),
    (2, 'Moderate'),
    (3, 'High'),
    (4, 'Advanced'),
    (5, 'Extreme'),
    ]
    
    title = models.CharField(max_length=30, null=False, blank=False)
    message = models.TextField(null=False, blank=False)
    complexity = models.IntegerField(choices=COMPLEXITY_CHOICES,null=False, blank=False)
    deadline = models.DateField(null=False, blank=False)
    raised_by = models.ForeignKey(User, on_delete=models.CASCADE)
    status =  models.IntegerField(choices=STATUS_CHOICES, default=1, null=False, blank=False)
    created_at = models.DateField(auto_now_add=True, null=False, blank=False)

class Assign(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    issue_id = models.ForeignKey(Issue, on_delete=models.CASCADE)

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Issue, Assign

class HomeView(LoginRequiredMixin,View):
  
  login_url = '/login'

  def get(self, request):

    issues = Issue.objects.all()
    return render(request, 'main/home.html', {"issues":issues, "page":"home"})

class DashboardView(LoginRequiredMixin,View):
  
  login_url = '/login'

  def get(self, request):
    issues = Issue.objects.filter(id__in=Assign.objects.filter(user_id=request.user.id))
    return render(request, 'main/home.html', {"issues":issues, "page":"dashboard"})

class RegisterView(View):

  def get(self, request):
    if not request.user.is_authenticated:
      return render(request, 'main/register.html', {})
    else:
      return HttpResponseRedirect('/')

  def post(self, request, *args, **kwargs):
    
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    email = request.POST['email']
    password = request.POST['password']
    username = email.split('@')[0]
    
    user = User.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
    user.save()
    return HttpResponseRedirect('login')


class LoginView(View):

  def get(self, request):
    if not request.user.is_authenticated:
      return render(request, 'main/login.html', {})
    else:
      return HttpResponseRedirect('/')

  def post(self, request, *args, **kwargs):
    email = request.POST['email']
    password = request.POST['password']
    username = email.split('@')[0]

    user = authenticate(username=username, password=password)
    if user is not None:
      login(request, user)
      return HttpResponseRedirect('/')
    else:
      return HttpResponseRedirect('login')

class CreateView(LoginRequiredMixin,View):
  
  login_url = '/login'

  def get(self, request):
    return render(request, 'main/create_issue.html', {})
  
  def post(self, request, *args, **kwargs):

    title = request.POST['title'] 
    message = request.POST['message']
    complexity = request.POST['complexity']
    deadline = request.POST['deadline'] 

    issue = Issue(title=title, message=message, complexity=complexity, deadline=deadline, raised_by=request.user)
    issue.save()
    
    return HttpResponseRedirect('/')

class AssignView(LoginRequiredMixin,View):
  
  login_url = '/login'

  def get(self, request):
    
    issue_id = request.GET["picked"]
    issue = Issue.objects.get(id=issue_id)

    assigned = Assign(user_id=request.user, issue_id=issue)
    assigned.save()

    issue.status = 2
    issue.save()

    return HttpResponseRedirect('/')

class CompleteView(LoginRequiredMixin,View):
  
  login_url = '/login'

  def get(self, request):
    
    issue_id = request.GET["complete"]
    issue = Issue.objects.get(id=issue_id)

    issue.status = 3
    issue.save()

    return HttpResponseRedirect('dashboard')
  
class LogoutView(View):

  def get(self, request):
    logout(request)
    return HttpResponseRedirect('login')

main/templates/main/base.html
{% load static %}

<!doctype html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

  <div class="isolate bg-white py-24 px-6 sm:py-32 lg:px-8">
    <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
      <svg class="relative left-1/2 -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-40rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678">
        <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
        <defs>
          <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
            <stop stop-color="#9089FC" />
            <stop offset="1" stop-color="#FF80B5" />
          </linearGradient>
        </defs>
      </svg>
    </div>
    
    {% block body %}    {% endblock %}
  </div>
</body>
</html>

main/templates/main/create_issue.html
{% extends "main/base.html" %}

{% block title %}  collabQ  {% endblock %}

{% block body %}

    <div class="mx-auto max-w-2xl text-center">
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Create New Issue</h2>
    </div>

    <form method="POST" class="mx-auto mt-16 max-w-xl sm:mt-20">    
    
      {% csrf_token %}
    
      <div class="grid grid-cols-1 gap-y-6 gap-x-8 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <label for="title" class="block text-sm font-semibold leading-6 text-gray-900">Title</label>
          <div class="mt-2.5">
            <input type="text" name="title" id="title" autocomplete="organization" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="message" class="block text-sm font-semibold leading-6 text-gray-900">Message</label>
          <div class="mt-2.5">
            <textarea name="message" id="message" rows="4" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600"></textarea>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="complexity" class="block text-sm font-semibold leading-6 text-gray-900">Select an option</label>
          <div class="mt-2.5">
            <select id="complexity" name="complexity" class="block w-half rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
              <option selected disabled>Choose a Complexity Level</option>
              <option value="1">Level 1 - Simple</option>
              <option value="2">Level 2 - Moderate</option>
              <option value="3">Level 3 - High</option>
              <option value="4">Level 4 - Advanced</option>
              <option value="5">Level 5 - Extreme</option>
            </select>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="deadline" class="block text-sm font-semibold leading-6 text-gray-900">Deadline</label>
          <div class="mt-2.5">
            <input type="date" name="deadline" id="deadline" class="block w-half rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
          </div>
        </div>

      </div>

      <div class="mt-10">
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <button type="submit" class="block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create</button>
          <a href="{% url 'main:home'%}" class="block w-full rounded-md bg-purple-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-purple-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-600">Back To Home</a>
      </div>
        
      </div>
    </form>

{% endblock %}

main/templates/main/dashboard.html
{% extends "main/base.html" %}

{% block title %}  collabQ  {% endblock %}

{% block body %}



<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <div class="mb-5 mx-auto max-w-2xl text-center">
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-3">
            <a href="{% url 'main:home'%}" class="text-white bg-gradient-to-r from-indigo-500 via-indigo-600 to-indigo-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-indigo-300 dark:focus:ring-indigo-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Back To Home</a>
            <a href="{% url 'main:dashboard'%}" class="text-white bg-gradient-to-r from-indigo-500 via-indigo-600 to-indigo-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-indigo-300 dark:focus:ring-indigo-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Dashboard</a>
            <a href="{% url 'main:logout'%}" class="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Logout</a>
        </div>
    </div>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">Created At</th>
                <th scope="col" class="px-6 py-3">Title</th>
                <th scope="col" class="px-6 py-3">Description</th>
                <th scope="col" class="px-6 py-3">Complexity</th>
                <th scope="col" class="px-6 py-3">raised_by</th>
                <th scope="col" class="px-6 py-3">Status</th>
                <th scope="col" class="px-6 py-3">deadline</th>
            </tr>
        </thead>
        <tbody>
            {% for i in issues %}
            <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ i.created_at }}
                </th>
                <td class="px-6 py-4">{{ i.title }}</td>
                <td class="px-6 py-4">{{ i.message }}</td>
                <td class="px-6 py-4">
                    {% if i.complexity == 1 %}
                    <span class="bg-gray-100 text-gray-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-gray-700 dark:text-gray-300">Simple</span>
                    {% elif i.complexity == 2 %}
                    <span class="bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">Moderate</span>
                    {% elif i.complexity == 3 %}
                    <span class="bg-purple-100 text-purple-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-purple-900 dark:text-purple-300">High</span>
                    {% elif i.complexity == 4 %}
                    <span class="bg-yellow-100 text-yellow-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300">Advanced</span>
                    {% elif i.complexity == 5 %}
                    <span class="bg-red-100 text-red-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-red-900 dark:text-red-300">Extreme</span>
                    {% endif %}
                </td>
                <td class="px-6 py-4">{{ i.raised_by.first_name }} {{i.raised_by.last_name }}</td>
                <td class="px-6 py-4">
                    <div class="flex items-center">
                        {% if i.status == 1 %}
                        <div class="h-2.5 w-2.5 rounded-full bg-green-500 mr-2"></div> Open
                        {% elif i.status == 2 %}
                        <div class="h-2.5 w-2.5 rounded-full bg-yellow-500 mr-2"></div> Picked
                        {% elif i.status == 3 %}
                        <div class="h-2.5 w-2.5 rounded-full bg-red-500 mr-2"></div> Completed
                        {% endif %}
                    </div>
                </td>
                <td class="px-6 py-4">{{ i.deadline }}</td>
                <td class="px-6 py-4">
                    {% if i.status == 1 %}
                    <a href="{% url 'main:assign'%}?picked={{ i.id }}" class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-200 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" >Choose</a>
                    {% else %}
                    <a href="#" class="text-gray-900 bg-gradient-to-r from-gray-200 via-gray-200 to-gray-500 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Mak</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

main/templates/main/home.html
{% extends "main/base.html" %}

{% block title %}  collabQ  {% endblock %}

{% block body %}



<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <div class="mb-5 mx-auto max-w-2xl text-center">
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-3">
            {% if page == 'home' %}
            <a href="{% url 'main:dashboard'%}" class="text-white bg-gradient-to-r from-indigo-500 via-indigo-600 to-indigo-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-indigo-300 dark:focus:ring-indigo-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Dashboard</a>
            {% else %}
            <a href="{% url 'main:home'%}" class="text-white bg-gradient-to-r from-indigo-500 via-indigo-600 to-indigo-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-indigo-300 dark:focus:ring-indigo-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Back To Home</a>
            {% endif %}
            <a href="{% url 'main:create'%}" class="text-white bg-gradient-to-r from-indigo-500 via-indigo-600 to-indigo-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-indigo-300 dark:focus:ring-indigo-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Create New Issue</a>
            <a href="{% url 'main:logout'%}" class="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Logout</a>
        </div>
    </div>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">Created At</th>
                <th scope="col" class="px-6 py-3">Title</th>
                <th scope="col" class="px-6 py-3">Description</th>
                <th scope="col" class="px-6 py-3">Complexity</th>
                <th scope="col" class="px-6 py-3">raised_by</th>
                <th scope="col" class="px-6 py-3">Status</th>
                <th scope="col" class="px-6 py-3">deadline</th>
            </tr>
        </thead>
        <tbody>
            {% for i in issues %}
            <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{ i.created_at }}
                </th>
                <td class="px-6 py-4">{{ i.title }}</td>
                <td class="px-6 py-4">{{ i.message }}</td>
                <td class="px-6 py-4">
                    {% if i.complexity == 1 %}
                    <span class="bg-gray-100 text-gray-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-gray-700 dark:text-gray-300">Simple</span>
                    {% elif i.complexity == 2 %}
                    <span class="bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">Moderate</span>
                    {% elif i.complexity == 3 %}
                    <span class="bg-purple-100 text-purple-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-purple-900 dark:text-purple-300">High</span>
                    {% elif i.complexity == 4 %}
                    <span class="bg-yellow-100 text-yellow-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300">Advanced</span>
                    {% elif i.complexity == 5 %}
                    <span class="bg-red-100 text-red-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-red-900 dark:text-red-300">Extreme</span>
                    {% endif %}
                </td>
                <td class="px-6 py-4">{{ i.raised_by.first_name }} {{i.raised_by.last_name }}</td>
                <td class="px-6 py-4">
                    <div class="flex items-center">
                        {% if i.status == 1 %}
                        <div class="h-2.5 w-2.5 rounded-full bg-green-500 mr-2"></div> Open
                        {% elif i.status == 2 %}
                        <div class="h-2.5 w-2.5 rounded-full bg-yellow-500 mr-2"></div> Picked
                        {% elif i.status == 3 %}
                        <div class="h-2.5 w-2.5 rounded-full bg-red-500 mr-2"></div> Completed
                        {% endif %}
                    </div>
                </td>
                <td class="px-6 py-4">{{ i.deadline }}</td>
                <td class="px-6 py-4">
                    {% if page == 'home' %}
                        {% if i.status == 1 %}
                        <a href="{% url 'main:assign'%}?picked={{ i.id }}" class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-200 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" >Pick</a>
                        {% else %}
                        <a href="#" class="text-gray-900 bg-gradient-to-r from-gray-200 via-gray-200 to-gray-500 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Picked</a>
                        {% endif %}
                    {% else %}
                        {% if i.status == 2 %}
                        <a href="{% url 'main:complete'%}?complete={{ i.id }}" class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-200 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" >Done</a>
                        {% else %}
                        <a href="#" class="text-gray-900 bg-gradient-to-r from-gray-200 via-gray-200 to-gray-500 hover:bg-gradient-to-br font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Completed</a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

main/templates/main/login.html
{% extends "main/base.html" %}

{% block title %}  collabQ  {% endblock %}

{% block body %}


  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Login</h2>
  </div>

  <form method="POST" class="mx-auto mt-16 max-w-xl sm:mt-20">
        
    {% csrf_token %}
    
    <div class="grid grid-cols-1 gap-y-6 gap-x-8 sm:grid-cols-2">

      <div class="sm:col-span-2">
        <label for="email" class="block text-sm font-semibold leading-6 text-gray-900">Email</label>
        <div class="mt-2.5">
          <input type="email" name="email" id="email" autocomplete="email" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
      </div>
      
	 <div class="sm:col-span-2">
        <label for="password" class="block text-sm font-semibold leading-6 text-gray-900">Password</label>
        <div class="mt-2.5">
          <input type="password" name="password" id="password" autocomplete="password" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
      </div>
    </div>
    <div class="mt-10">
      <button type="submit" class="block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Login</button>
    </div>
    <div class="mt-10">
      <a href="{% url 'main:register'%}" class="block w-full px-3.5 py-2.5 text-center text-sm font-semibold shadow-sm font-medium text-indigo-600 hover:text-indigo-500 ">Create New Account </a>
    </div>
  </form>


{% endblock %}

main/templates/main/register.html
{% extends "main/base.html" %}

{% block title %}  collabQ  {% endblock %}

{% block body %}

  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Registration</h2>
  </div>

  <form method="POST" class="mx-auto mt-16 max-w-xl sm:mt-20">
    
    {% csrf_token %}
    
    <div class="grid grid-cols-1 gap-y-6 gap-x-8 sm:grid-cols-2">
      <div>
        <label for="first-name" class="block text-sm font-semibold leading-6 text-gray-900">First name</label>
        <div class="mt-2.5">
          <input type="text" name="first_name" id="first-name" autocomplete="given-name" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
      </div>
      <div>
        <label for="last-name" class="block text-sm font-semibold leading-6 text-gray-900">Last name</label>
        <div class="mt-2.5">
          <input type="text" name="last_name" id="last-name" autocomplete="family-name" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
      </div>

      <div class="sm:col-span-2">
        <label for="email" class="block text-sm font-semibold leading-6 text-gray-900">Email</label>
        <div class="mt-2.5">
          <input type="email" name="email" id="email" autocomplete="email" class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
      </div>
      
	 <div class="sm:col-span-2">
        <label for="password" class="block text-sm font-semibold leading-6 text-gray-900">Password</label>
        <div class="mt-2.5">
          <input type="password" name="password" id="password" autocomplete="password" onkeyup='check();' class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
      </div>

	 <div class="sm:col-span-2">
        <label for="confirm_password" class="block text-sm font-semibold leading-6 text-gray-900">Confirm Password</label>
        <div class="mt-2.5">
          <input type="password" name="confirm_password" id="confirm_password" autocomplete="confirm_password" onkeyup='check();' class="block w-full rounded-md border-0 py-2 px-3.5 text-sm leading-6 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600">
        </div>
		    <span id='message'></span>
      </div>
    </div>

    <div class="mt-10">
      <button type="submit" class="block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Register</button>
    </div>
    <div class="mt-10">
      <a href="{% url 'main:login'%}" class="block w-full px-3.5 py-2.5 text-center text-sm font-semibold shadow-sm font-medium text-indigo-600 hover:text-indigo-500 ">Already have an account?</a>
    </div>
  </form>



<script>
var check = function() {
  if (document.getElementById('password').value == document.getElementById('confirm_password').value) {
    document.getElementById('message').style.color = 'green';
    document.getElementById('message').innerHTML = 'Confirmed Password Matched';
  } else {
    document.getElementById('message').style.color = 'red';
    document.getElementById('message').innerHTML = 'Confirmed Password is Not Matching';
  }
}
</script>

{% endblock %}